package com.yotpo.orders.kafka.dto;

import com.yotpo.orders.api.dto.request.CreateOrderRequest;
import lombok.*;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Kafka message DTO for order data.
 * Sent to orders.incoming topic by API, consumed by order processor.
 *
 * Design: Contains all data needed to create order without additional lookups.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderMessage {

    /**
     * Order ID (UUID generated by API).
     */
    private UUID orderId;

    /**
     * Store identifier (used as Kafka partition key).
     */
    private String storeId;

    /**
     * Shopper information.
     */
    private ShopperData shopper;

    /**
     * When the order was placed (from merchant).
     */
    private OffsetDateTime orderDate;

    /**
     * Line items (products purchased).
     */
    private List<LineItemData> lineItems;

    /**
     * When the message was created.
     */
    private OffsetDateTime createdAt;

    /**
     * Shopper data nested DTO.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class ShopperData {
        private String email;
        private String firstName;
        private String lastName;
    }

    /**
     * Line item data nested DTO.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class LineItemData {
        private String externalProductId;
        private String productName;
        private String productDescription;
        private BigDecimal productPrice;
        private Integer quantity;
    }

    /**
     * Create OrderMessage from API request.
     */
    public static OrderMessage fromRequest(UUID orderId, String storeId, CreateOrderRequest request) {
        return OrderMessage.builder()
            .orderId(orderId)
            .storeId(storeId)
            .shopper(ShopperData.builder()
                .email(request.getEmail())
                .firstName(request.getFirstName())
                .lastName(request.getLastName())
                .build())
            .orderDate(request.getOrderDate())
            .lineItems(request.getLineItems().stream()
                .map(item -> LineItemData.builder()
                    .externalProductId(item.getExternalProductId())
                    .productName(item.getProductName())
                    .productDescription(item.getProductDescription())
                    .productPrice(item.getProductPrice())
                    .quantity(item.getQuantity())
                    .build())
                .collect(Collectors.toList()))
            .createdAt(OffsetDateTime.now())
            .build();
    }
}
