package com.yotpo.orders.domain.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Order entity representing a purchase transaction from a merchant.
 *
 * Design Decisions:
 * - UUID primary key: Generated by API for async 202 response pattern
 * - store_id denormalized: Enables efficient queries without JOIN to shoppers
 * - Relationship to Shopper: Many orders can belong to one shopper
 * - Relationship to LineItems: One order has many line items (cascade delete)
 *
 * Business Context:
 * - Orders are immutable historical records
 * - created_at is when consumer processed the order (used in domain events)
 * - order_date is when the purchase was made (from merchant)
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    /**
     * Primary key - UUID generated by API.
     * Enables async 202 Accepted response without waiting for DB.
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Store identifier (denormalized from shopper for query efficiency).
     * Allows filtering by store without joining shoppers table.
     */
    @Column(name = "store_id", nullable = false, length = 255)
    private String storeId;

    /**
     * Reference to the shopper who placed this order.
     * Many orders can belong to one shopper.
     * RESTRICT delete: Cannot delete shopper with existing orders.
     * LAZY fetch: Loaded on demand to avoid N+1 queries in list operations.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "shopper_id",
        nullable = false,
        foreignKey = @ForeignKey(name = "fk_orders_shopper")
    )
    private Shopper shopper;

    /**
     * When the order was placed (from merchant).
     * This is the business date of the purchase.
     */
    @Column(name = "order_date", nullable = false)
    private OffsetDateTime orderDate;

    /**
     * When the order was persisted to database (by consumer).
     * Used as "created_at" in domain events.
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    /**
     * Line items (purchased products) in this order.
     * Cascade ALL: Line items are created/deleted with order.
     * orphanRemoval: Removing line item from list deletes it from DB.
     */
    @OneToMany(
        mappedBy = "order",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.LAZY
    )
    @Builder.Default
    private List<LineItem> lineItems = new ArrayList<>();

    /**
     * Set creation timestamp before persisting.
     */
    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now();
        }
    }

    /**
     * Helper method to add a line item to the order.
     * Maintains bidirectional relationship.
     *
     * @param lineItem the line item to add
     */
    public void addLineItem(LineItem lineItem) {
        lineItems.add(lineItem);
        lineItem.setOrder(this);
    }

    /**
     * Helper method to remove a line item from the order.
     * Maintains bidirectional relationship.
     *
     * @param lineItem the line item to remove
     */
    public void removeLineItem(LineItem lineItem) {
        lineItems.remove(lineItem);
        lineItem.setOrder(null);
    }
}
