-- ============================================
-- V2: Create Orders Table
-- ============================================
-- Orders represent purchase transactions from merchants.
--
-- Design Decisions:
--   - UUID primary key: Generated by API for async 202 response
--   - Foreign key to shoppers: Normalized relationship
--   - store_id duplicated: For efficient queries without JOIN
--
-- ============================================

CREATE TABLE orders (
    -- Primary key: UUID generated by API (enables async response)
    -- Using UUID allows returning order_id immediately without DB round-trip
    id UUID PRIMARY KEY,

    -- Store identifier (denormalized for query efficiency)
    -- Allows filtering by store without joining shoppers table
    store_id VARCHAR(255) NOT NULL,

    -- Foreign key to shoppers table
    -- ON DELETE RESTRICT: Cannot delete shopper with orders
    shopper_id BIGINT NOT NULL,

    -- Order date (from merchant - when order was placed)
    -- Stored with timezone for international support
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Database creation timestamp (when consumer processed the order)
    -- Used in domain events as "created_at"
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Foreign key constraint
    CONSTRAINT fk_orders_shopper
        FOREIGN KEY (shopper_id)
        REFERENCES shoppers(id)
        ON DELETE RESTRICT
);

-- Add comments for documentation
COMMENT ON TABLE orders IS 'Purchase orders from merchants. UUID enables async API response.';
COMMENT ON COLUMN orders.id IS 'UUID generated by API - enables 202 Accepted without DB round-trip';
COMMENT ON COLUMN orders.store_id IS 'Denormalized store_id for query efficiency';
COMMENT ON COLUMN orders.order_date IS 'When the order was placed (merchant time)';
COMMENT ON COLUMN orders.created_at IS 'When order was persisted to DB (used in domain events)';
