-- ============================================
-- V5: Create Retry Queue Table
-- ============================================
-- Stores orders that failed to publish to Kafka.
--
-- Purpose:
--   - High availability: API always returns 202 Accepted
--   - If Kafka is down, orders are queued for retry
--   - Background job retries with exponential backoff
--
-- Lifecycle:
--   1. API tries to publish to Kafka
--   2. On failure, order is inserted into retry_queue
--   3. Background job (every 5s) retries pending entries
--   4. On success, entry is deleted from queue
--   5. On failure, retry_count++ and next_retry_at updated
--
-- ============================================

CREATE TABLE retry_queue (
    -- Primary key: Auto-generated UUID
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Order ID (UUID generated by API)
    -- Used for logging and correlation
    order_id UUID NOT NULL,

    -- Store ID (partition key for Kafka)
    store_id VARCHAR(255) NOT NULL,

    -- Complete Kafka message payload (JSON)
    -- Contains all order data needed for retry
    message_payload JSONB NOT NULL,

    -- Retry tracking
    retry_count INTEGER NOT NULL DEFAULT 0,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- When to attempt next retry (exponential backoff)
    next_retry_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Last error message (for debugging)
    last_error TEXT,

    -- Constraints
    CONSTRAINT chk_retry_queue_retry_count
        CHECK (retry_count >= 0)
);

-- Index for efficient retry processing
-- Query: SELECT * FROM retry_queue WHERE next_retry_at <= NOW() ORDER BY next_retry_at LIMIT 100
CREATE INDEX idx_retry_queue_next_retry
    ON retry_queue(next_retry_at)
    WHERE retry_count < 100;  -- Partial index: ignore entries that exceeded max retries

-- Index for order lookup (debugging/monitoring)
CREATE INDEX idx_retry_queue_order_id
    ON retry_queue(order_id);

-- Comments
COMMENT ON TABLE retry_queue IS 'Orders pending Kafka publish - API high availability mechanism';
COMMENT ON COLUMN retry_queue.message_payload IS 'Complete OrderMessage JSON for Kafka publish';
COMMENT ON COLUMN retry_queue.next_retry_at IS 'Scheduled retry time (exponential backoff)';
COMMENT ON INDEX idx_retry_queue_next_retry IS 'Efficient retry batch selection';
